"use strict";
/* ================= 工具 ================= */
const $=s=>document.querySelector(s);
const rand=(a,b)=>a+Math.random()*(b-a);
const irand=(a,b)=>Math.floor(rand(a,b+1));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const alive=a=>a.filter(u=>u.alive);

/* ================= 像素画 ================= */
const PAL={
  jon:{K:'#16161f',F:'#e8b98f',E:'#20222c',C:'#262a36',D:'#3d332a',W:'#9096a4',B:'#12141c',S:'#d3dcea',G:'#c9a55a'},
  dany:{W:'#eef1f6',F:'#f2cba4',E:'#274',U:'#4a7ab5',L:'#d3e4f6',B:'#262c3a'},
  arya:{N:'#5a4632',F:'#eec39a',E:'#22242e',A:'#4a4c56',B:'#15171f',S:'#dde3ec',G:'#98a0ae'},
  bri:{Y:'#d9b36a',F:'#e8b98f',E:'#232630',M:'#8d99a8',O:'#c9a55a',S:'#e2e8f0',B:'#1a1d26'},
  wight:{R:'#7d8a78',B:'#7de8ff',T:'#3a404c',D:'#1c1f28'},
  walker:{I:'#cfe4ef',C:'#9fc6da',B:'#45d6ff',K:'#28323f',H:'#66798c',P:'#c4ecff'},
  nk:{I:'#b6cfdd',N:'#5a7383',B:'#54d8ff',M:'#394a58',K:'#161f2a'},
  dragon:{K:'#181020',M:'#43283d',R:'#b8453a',O:'#ffc45e'},
  spider:{L:'#b9d4e8',B:'#66f0ff',G:'#4a607a',T:'#7d9cb8'},
  giant:{F:'#6b5138',S:'#c9a080',E:'#ffd28f',C:'#4a3a28'},
  wolf:{H:'#8d99a8',D:'#5a6a7c',E:'#ffd28f',K:'#20242e',W:'#dfe7f2'}
};
const SPR={
jon:[
".....KKKKK.......",
"....KKKKKKK......",
"....KFFFFFK......",
"....KFEFEFK......",
"....KFFFFFK......",
".....FFFFF.......",
"....WWWWWWW......",
"...CCCCCCCCC.....",
"..CCCCCCCCCC..S..",
"..C.DDDDDDDC..S..",
"..C.DDDDDDDC..S..",
"..C.DDDDDDDC..S..",
"...CCCCCCCCC.GGG.",
"....DDDDDDD......",
"....DD...DD......",
"....DD...DD......",
"....BB...BB......"],
dany:[
"....WWWWWW......",
"...WWWWWWWW.....",
"...WFFFFFFW.....",
"...WFEFEFFW.....",
"...WFFFFFFW.....",
"...WWFFFFWW.....",
"....UUUUUU......",
"...UUUUUUUU.....",
"...UULLLLUU.....",
"...UUUUUUUU.....",
"...UUUUUUUU.....",
"...UUUUUUUU.....",
"..UUUUUUUUUU....",
"..UUUUUUUUUU....",
"..UUUUUUUUUU....",
"..UUUUUUUUUU....",
"...BB....BB....."],
arya:[
".....NNNNN......",
"....NNNNNNN.....",
"....NFFFFFN.....",
"....NFEFEFN.....",
"....NFFFFFN.....",
".....FFFFF......",
"....AAAAAAA.....",
"...AAAAAAAAA....",
"..A.AAAAAAAA.S..",
"..A.AAAAAAAA.S..",
"...AAAAAAAAA.G..",
"....AAAAAAA.....",
"....AA...AA.....",
"....AA...AA.....",
"....BB...BB....."],
bri:[
".....YYYYY.......",
"....YYYYYYY......",
"....YFFFFFY......",
"....YFEFEFY......",
"....YFFFFFY......",
".....FFFFF.......",
"...MMMMMMMMM.....",
"..MMOMMMMMOMM..S.",
"..MMMMMMMMMMM..S.",
"..MMMMMMMMMMM..S.",
"..MMMMMMMMMMM..S.",
"...MMMMMMMMM..GG.",
"....MMMMMMM......",
"....MM...MM......",
"....MM...MM......",
"....MM...MM......",
"....BB...BB......"],
wight:[
"....RRRR.......",
"...RRRRRR......",
"...RBBRRR......",
"...RRRRRRR.....",
"....RRRR.......",
".....RR........",
"...TTTTTTT.....",
"..TTTTTTTTT....",
"..T.TTTTTT.....",
"....TTTTTTT....",
"....TTTTTTT....",
".....TT.TT.....",
".....TT.TT.....",
".....DD.DD....."],
walker:[
"...C..C..C......",
"...CIIIIC.......",
"...IIIIIII......",
"..IIBIIIIBI.....",
"...IIIIIII......",
"....IIIII.......",
".....III........",
"..KKKKKKKKK..P..",
"..KKKKKKKKK..PP.",
"..K.KKKKKKK..P..",
"..K.KKKKKKK..H..",
"....KKKKKKK..H..",
"....KKKKKKK..H..",
"....KK...KK..H..",
"....KK...KK..H..",
"....II...II.....",
"....II...II....."],
nk:[
"..N...N..N...N....",
"..NN..N..N..NN....",
"..IIIIIIIIIIII....",
"..IIBBIIIIBBII....",
"..IIIIIIIIIIII....",
"...IIIIMMIIII.....",
"..KKKKKKKKKKKK....",
".KKKKKKKKKKKKKK...",
".K.KKKKKKKKKKKK...",
".K.KKKKKKKKKKKK...",
".K.KKKKKKKKKKKK...",
"...KKKKKKKKKKK....",
"...KKKKKKKKKKK....",
"...KKKKKKKKKKK....",
"...KKK.....KKK....",
"...III.....III....",
"...III.....III...."],
spider:[
"..T............T..",
"...T....LL....T...",
"....T.LLLLLL.T....",
".LLLLLLLLLLLLLLLL.",
".LLBBLLLLLLBBLLLL.",
"..LLLLLLLLLLLLLL..",
".T.LLLLLLLLLLLL.T.",
"..T.LLLLLLLLLL.T..",
"...T.LLLLLLLL.T...",
"....T..LLLL..T...."],
giant:[
"....SSSSSS......",
"...SSSSSSSS.....",
"...SESSESSS.....",
"...SSSSSSSS.....",
"....SSSSSS......",
"..FFFFFFFFFF....",
".FFFFFFFFFFF.CC.",
".FF.FFFFFF.F..C.",
".FF.FFFFFF.F..C.",
".FF.FFFFFF.F..C.",
".FFFFFFFFFFF..C.",
"..FFFFFFFFFF.C..",
"..FFFFFFFFFF....",
"..FFF....FFF....",
"..FFF....FFF....",
".FFF......FFF..."],
wolf:[
"................",
"................",
"..D.D...........",
"..DDD...........",
".DHHHDK.........",
".DHEHHK.........",
".DHHHHKK........",
"..KHHHHHK.......",
"...HHHHHHHK.....",
"..HHHHHHHHHK....",
"..HHHHHHHHHHWW..",
"...HH....HHH....",
"...HD....HH.....",
"...DD....DD....."],
dragonA:[
"..............MM........................",
".............MMMM.......................",
"............MMMMMM......................",
"...........MMMMMMMM.....................",
"....KK.....MMMMMMMMMM...................",
"...KKKK.....MMMMMMMM....................",
"..KKOKKK.....MMMMMM.....................",
".KKKKKKKK.....MMMM......................",
".KKKKKKKKKK....MM.......................",
".KRRKKKKKKKKKKKKKKKKKKKKKKKK............",
"..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.......",
"...KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK....",
"....KKKK...KKKK...KKKK...........KKKKK..",
"....KK.....KK......KK..............KK..."],
dragonB:[
"........................................",
"........................................",
"............MM..........................",
"....KK....MMMM..........................",
"...KKKK..MMMMMM.........................",
"..KKOKKK.MMMMMMMM.......................",
".KKKKKKKKMMMMMMMMMM.....................",
".KKKKKKKKKKMMMMMMMMMMM..................",
".KRRKKKKKKKKKKKKKKKKKKKKKKKK............",
"..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.......",
"...KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK....",
"....KKKK...KKKK...KKKK...........KKKKK..",
"....KK.....KK......KK..............KK..."]
};
function makeSprite(spr,pal){
  const h=spr.length,w=Math.max(...spr.map(r=>r.length));
  const solid=(r,c)=>{const ch=spr[r]&&spr[r][c];return ch&&ch!=='.'&&ch!==' ';};
  const c=document.createElement('canvas');c.width=w+2;c.height=h+2;
  const x=c.getContext('2d');
  x.fillStyle='#05070d';
  for(const[ox,oy]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]])
    for(let r=0;r<h;r++)for(let cc=0;cc<w;cc++)if(solid(r,cc))x.fillRect(cc+1+ox,r+1+oy,1,1);
  for(let r=0;r<h;r++)for(let cc=0;cc<spr[r].length;cc++){
    if(!solid(r,cc))continue;x.fillStyle=pal[spr[r][cc]]||'#f0f';x.fillRect(cc+1,r+1,1,1);
  }
  const f=document.createElement('canvas');f.width=c.width;f.height=c.height;
  const fx=f.getContext('2d');fx.drawImage(c,0,0);
  fx.globalCompositeOperation='source-in';fx.fillStyle='#fff';fx.fillRect(0,0,f.width,f.height);
  return {img:c,flash:f,w:c.width,h:c.height};
}
const DRA={a:makeSprite(SPR.dragonA,PAL.dragon),b:makeSprite(SPR.dragonB,PAL.dragon)};
